### ISSUE TITLE
pypi stratuslab-libcloud-drivers 13.10.0 

### ISSUE THREAD

**Issue by vgauthier** [StratusLab/libcloud-drivers#5]
It seems that in the setup.py of the stratuslab-libcloud-drivers, it require to install  "apache-libcloud ==0.12.4", instead of the one that is compliant with the newest version of newest version of stratuslab-libcloud-drivers

regards, 
Vincent

**Comment by loomis** [comment]
Fixed will be deployed to pypi when release is announced.
